{% set version = "0.1.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-simcdm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/simcdm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/simcdm/simcdm_{{ version }}.tar.gz
  sha256: e117ad0b2d4db3c3fe8d1b7a0e91b4bd8c2864345653d82fb64ad943550c90df

build:
  merge_build_host: true  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  host:
    - r-base
    - r-rcpp >=1.0.11
    - r-rcpparmadillo >=0.12.6.6.0
    - libblas
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=1.0.11
    - r-rcpparmadillo >=0.12.6.6.0

test:
  commands:
    - $R -e "library('simcdm')"           # [not win]
    - "\"%R%\" -e \"library('simcdm')\""  # [win]

about:
  home: https://tmsalab.github.io/simcdm/
  dev_url: https://github.com/tmsalab/simcdm
  license: GPL-2.0-or-later
  summary: 'Provides efficient R and ''C++'' routines to simulate cognitive diagnostic model data for Deterministic Input, Noisy "And" Gate (''DINA'') and reduced Reparameterized Unified Model (''rRUM'') from Culpepper and Hudson (2017) <doi: 10.1177/0146621617707511>, Culpepper (2015) <doi:10.3102/1076998615595403>, and
    de la Torre (2009) <doi:10.3102/1076998607309474>.'
  license_family: GPL-2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - coatless
    - steveculpepper
